var annotated_dup =
[
    [ "_BasicSensorData", "struct__BasicSensorData.html", null ],
    [ "_CommandMessage", "struct__CommandMessage.html", null ],
    [ "_Heartbeat", "struct__Heartbeat.html", null ],
    [ "_SimpleMessage", "struct__SimpleMessage.html", null ],
    [ "_TelemetryMessage", "struct__TelemetryMessage.html", null ],
    [ "AccelerometerDataMsg", "structAccelerometerDataMsg.html", null ],
    [ "ADXL375", "classADXL375.html", "classADXL375" ],
    [ "ArduinoTextLogger", "classArduinoTextLogger.html", null ],
    [ "BarometerDataMsg", "structBarometerDataMsg.html", null ],
    [ "FakeAccelerometer", "classFakeAccelerometer.html", "classFakeAccelerometer" ],
    [ "GNSSDataMsg", "structGNSSDataMsg.html", "structGNSSDataMsg" ],
    [ "GroundTelemetrySystem", "classGroundTelemetrySystem.html", null ],
    [ "GyroDataMsg", "structGyroDataMsg.html", null ],
    [ "MagnetometerDataMsg", "structMagnetometerDataMsg.html", null ],
    [ "MRAS_System", "classMRAS__System.html", "classMRAS__System" ],
    [ "NativeDataLogger", "classNativeDataLogger.html", "classNativeDataLogger" ],
    [ "NativeTextLogger", "classNativeTextLogger.html", "classNativeTextLogger" ],
    [ "QueueTelemetryMessageMsg", "structQueueTelemetryMessageMsg.html", null ],
    [ "ReceivedTelemetryMessageMsg", "structReceivedTelemetryMessageMsg.html", null ],
    [ "RocketTelemetrySystem", "classRocketTelemetrySystem.html", null ],
    [ "Sensor_ADXL375", "classSensor__ADXL375.html", null ],
    [ "Sensor_LIS3MDL", "classSensor__LIS3MDL.html", null ],
    [ "Sensor_LSM6DSO32", "classSensor__LSM6DSO32.html", null ],
    [ "Sensor_MS5607", "classSensor__MS5607.html", null ],
    [ "Sensor_ZOEM8Q", "classSensor__ZOEM8Q.html", "classSensor__ZOEM8Q" ],
    [ "Subsystem", "classSubsystem.html", "classSubsystem" ],
    [ "SystemMessage", "classSystemMessage.html", null ],
    [ "TelemetryDataMsg", "structTelemetryDataMsg.html", null ],
    [ "TelemetryMessage", "classTelemetryMessage.html", null ],
    [ "TelemetrySystem", "classTelemetrySystem.html", "classTelemetrySystem" ],
    [ "TextLogger", "classTextLogger.html", "classTextLogger" ],
    [ "TransferWindowAckMsg", "structTransferWindowAckMsg.html", null ],
    [ "TransferWindowInitMsg", "structTransferWindowInitMsg.html", null ]
];