/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_HIL_MESSAGES_PB_H_INCLUDED
#define PB_HIL_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ProtobufTextLogMsg {
    char text[255];
} ProtobufTextLogMsg;

typedef struct _ProtobufAccelerometerDataMsg {
    float x;
    float y;
    float z;
} ProtobufAccelerometerDataMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ProtobufTextLogMsg_init_default          {""}
#define ProtobufAccelerometerDataMsg_init_default {0, 0, 0}
#define ProtobufTextLogMsg_init_zero             {""}
#define ProtobufAccelerometerDataMsg_init_zero   {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ProtobufTextLogMsg_text_tag              1
#define ProtobufAccelerometerDataMsg_x_tag       1
#define ProtobufAccelerometerDataMsg_y_tag       2
#define ProtobufAccelerometerDataMsg_z_tag       3

/* Struct field encoding specification for nanopb */
#define ProtobufTextLogMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   text,              1)
#define ProtobufTextLogMsg_CALLBACK NULL
#define ProtobufTextLogMsg_DEFAULT NULL

#define ProtobufAccelerometerDataMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3)
#define ProtobufAccelerometerDataMsg_CALLBACK NULL
#define ProtobufAccelerometerDataMsg_DEFAULT NULL

extern const pb_msgdesc_t ProtobufTextLogMsg_msg;
extern const pb_msgdesc_t ProtobufAccelerometerDataMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ProtobufTextLogMsg_fields &ProtobufTextLogMsg_msg
#define ProtobufAccelerometerDataMsg_fields &ProtobufAccelerometerDataMsg_msg

/* Maximum encoded size of messages (where known) */
#define ProtobufAccelerometerDataMsg_size        15
#define ProtobufTextLogMsg_size                  257

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
