/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_MRAS_PB_H_INCLUDED
#define PB_MRAS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _AccelerometerType {
    AccelerometerType_UNKNOWN = 0,
    AccelerometerType_LOW_G = 2,
    AccelerometerType_HIGH_G = 1
} AccelerometerType;

/* Struct definitions */
typedef struct _ProtobufTextLogMsg {
    char text[255];
} ProtobufTextLogMsg;

typedef struct _ProtobufAccelerometerDataMsg {
    float x;
    float y;
    float z;
    AccelerometerType type;
} ProtobufAccelerometerDataMsg;

typedef struct _ProtobufMagnetometerDataMsg {
    float x;
    float y;
    float z;
} ProtobufMagnetometerDataMsg;

typedef struct _ProtobufBarometerDataMsg {
    float pressure;
    float temperature;
} ProtobufBarometerDataMsg;

typedef struct _ProtobufGNSSDataMsg {
    float latitude;
    float longitude;
    float altitude;
    float fixType;
    float SIV;
} ProtobufGNSSDataMsg;

typedef struct _MRASProtobufMsg {
    pb_size_t which_message;
    union {
        ProtobufAccelerometerDataMsg accelerometer_data;
        ProtobufTextLogMsg text_log;
        ProtobufMagnetometerDataMsg magnetometer_data;
        ProtobufBarometerDataMsg barometer_data;
        ProtobufGNSSDataMsg gnss_data;
    } message;
} MRASProtobufMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _AccelerometerType_MIN AccelerometerType_UNKNOWN
#define _AccelerometerType_MAX AccelerometerType_LOW_G
#define _AccelerometerType_ARRAYSIZE ((AccelerometerType)(AccelerometerType_LOW_G+1))


#define ProtobufAccelerometerDataMsg_type_ENUMTYPE AccelerometerType






/* Initializer values for message structs */
#define ProtobufTextLogMsg_init_default          {""}
#define ProtobufAccelerometerDataMsg_init_default {0, 0, 0, _AccelerometerType_MIN}
#define ProtobufMagnetometerDataMsg_init_default {0, 0, 0}
#define ProtobufBarometerDataMsg_init_default    {0, 0}
#define ProtobufGNSSDataMsg_init_default         {0, 0, 0, 0, 0}
#define MRASProtobufMsg_init_default             {0, {ProtobufAccelerometerDataMsg_init_default}}
#define ProtobufTextLogMsg_init_zero             {""}
#define ProtobufAccelerometerDataMsg_init_zero   {0, 0, 0, _AccelerometerType_MIN}
#define ProtobufMagnetometerDataMsg_init_zero    {0, 0, 0}
#define ProtobufBarometerDataMsg_init_zero       {0, 0}
#define ProtobufGNSSDataMsg_init_zero            {0, 0, 0, 0, 0}
#define MRASProtobufMsg_init_zero                {0, {ProtobufAccelerometerDataMsg_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define ProtobufTextLogMsg_text_tag              1
#define ProtobufAccelerometerDataMsg_x_tag       1
#define ProtobufAccelerometerDataMsg_y_tag       2
#define ProtobufAccelerometerDataMsg_z_tag       3
#define ProtobufAccelerometerDataMsg_type_tag    4
#define ProtobufMagnetometerDataMsg_x_tag        1
#define ProtobufMagnetometerDataMsg_y_tag        2
#define ProtobufMagnetometerDataMsg_z_tag        3
#define ProtobufBarometerDataMsg_pressure_tag    1
#define ProtobufBarometerDataMsg_temperature_tag 2
#define ProtobufGNSSDataMsg_latitude_tag         1
#define ProtobufGNSSDataMsg_longitude_tag        2
#define ProtobufGNSSDataMsg_altitude_tag         3
#define ProtobufGNSSDataMsg_fixType_tag          4
#define ProtobufGNSSDataMsg_SIV_tag              5
#define MRASProtobufMsg_accelerometer_data_tag   1
#define MRASProtobufMsg_text_log_tag             2
#define MRASProtobufMsg_magnetometer_data_tag    3
#define MRASProtobufMsg_barometer_data_tag       4
#define MRASProtobufMsg_gnss_data_tag            5

/* Struct field encoding specification for nanopb */
#define ProtobufTextLogMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   text,              1)
#define ProtobufTextLogMsg_CALLBACK NULL
#define ProtobufTextLogMsg_DEFAULT NULL

#define ProtobufAccelerometerDataMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3) \
X(a, STATIC,   SINGULAR, UENUM,    type,              4)
#define ProtobufAccelerometerDataMsg_CALLBACK NULL
#define ProtobufAccelerometerDataMsg_DEFAULT NULL

#define ProtobufMagnetometerDataMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3)
#define ProtobufMagnetometerDataMsg_CALLBACK NULL
#define ProtobufMagnetometerDataMsg_DEFAULT NULL

#define ProtobufBarometerDataMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    pressure,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       2)
#define ProtobufBarometerDataMsg_CALLBACK NULL
#define ProtobufBarometerDataMsg_DEFAULT NULL

#define ProtobufGNSSDataMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    latitude,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    longitude,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    altitude,          3) \
X(a, STATIC,   SINGULAR, FLOAT,    fixType,           4) \
X(a, STATIC,   SINGULAR, FLOAT,    SIV,               5)
#define ProtobufGNSSDataMsg_CALLBACK NULL
#define ProtobufGNSSDataMsg_DEFAULT NULL

#define MRASProtobufMsg_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,accelerometer_data,message.accelerometer_data),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,text_log,message.text_log),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,magnetometer_data,message.magnetometer_data),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,barometer_data,message.barometer_data),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,gnss_data,message.gnss_data),   5)
#define MRASProtobufMsg_CALLBACK NULL
#define MRASProtobufMsg_DEFAULT NULL
#define MRASProtobufMsg_message_accelerometer_data_MSGTYPE ProtobufAccelerometerDataMsg
#define MRASProtobufMsg_message_text_log_MSGTYPE ProtobufTextLogMsg
#define MRASProtobufMsg_message_magnetometer_data_MSGTYPE ProtobufMagnetometerDataMsg
#define MRASProtobufMsg_message_barometer_data_MSGTYPE ProtobufBarometerDataMsg
#define MRASProtobufMsg_message_gnss_data_MSGTYPE ProtobufGNSSDataMsg

extern const pb_msgdesc_t ProtobufTextLogMsg_msg;
extern const pb_msgdesc_t ProtobufAccelerometerDataMsg_msg;
extern const pb_msgdesc_t ProtobufMagnetometerDataMsg_msg;
extern const pb_msgdesc_t ProtobufBarometerDataMsg_msg;
extern const pb_msgdesc_t ProtobufGNSSDataMsg_msg;
extern const pb_msgdesc_t MRASProtobufMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ProtobufTextLogMsg_fields &ProtobufTextLogMsg_msg
#define ProtobufAccelerometerDataMsg_fields &ProtobufAccelerometerDataMsg_msg
#define ProtobufMagnetometerDataMsg_fields &ProtobufMagnetometerDataMsg_msg
#define ProtobufBarometerDataMsg_fields &ProtobufBarometerDataMsg_msg
#define ProtobufGNSSDataMsg_fields &ProtobufGNSSDataMsg_msg
#define MRASProtobufMsg_fields &MRASProtobufMsg_msg

/* Maximum encoded size of messages (where known) */
#define MRASProtobufMsg_size                     260
#define ProtobufAccelerometerDataMsg_size        17
#define ProtobufBarometerDataMsg_size            10
#define ProtobufGNSSDataMsg_size                 25
#define ProtobufMagnetometerDataMsg_size         15
#define ProtobufTextLogMsg_size                  257

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
