/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "telemetry.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Heartbeat, Heartbeat, AUTO)


PB_BIND(BasicSensorData, BasicSensorData, AUTO)


PB_BIND(CommandMessage, CommandMessage, AUTO)


PB_BIND(TelemetryMessage, TelemetryMessage, AUTO)




