# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MRAS.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nMRAS.proto\"\"\n\x12ProtobufTextLogMsg\x12\x0c\n\x04text\x18\x01 \x01(\t\"a\n\x1cProtobufAccelerometerDataMsg\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12 \n\x04type\x18\x04 \x01(\x0e\x32\x12.AccelerometerType\">\n\x1bProtobufMagnetometerDataMsg\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"A\n\x18ProtobufBarometerDataMsg\x12\x10\n\x08pressure\x18\x01 \x01(\x02\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\"j\n\x13ProtobufGNSSDataMsg\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x02\x12\x0f\n\x07\x66ixType\x18\x04 \x01(\x02\x12\x0b\n\x03SIV\x18\x05 \x01(\x02\"\x9d\x02\n\x0fMRASProtobufMsg\x12;\n\x12\x61\x63\x63\x65lerometer_data\x18\x01 \x01(\x0b\x32\x1d.ProtobufAccelerometerDataMsgH\x00\x12\'\n\x08text_log\x18\x02 \x01(\x0b\x32\x13.ProtobufTextLogMsgH\x00\x12\x39\n\x11magnetometer_data\x18\x03 \x01(\x0b\x32\x1c.ProtobufMagnetometerDataMsgH\x00\x12\x33\n\x0e\x62\x61rometer_data\x18\x04 \x01(\x0b\x32\x19.ProtobufBarometerDataMsgH\x00\x12)\n\tgnss_data\x18\x05 \x01(\x0b\x32\x14.ProtobufGNSSDataMsgH\x00\x42\t\n\x07message*7\n\x11\x41\x63\x63\x65lerometerType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05LOW_G\x10\x02\x12\n\n\x06HIGH_G\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MRAS_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACCELEROMETERTYPE._serialized_start=676
  _ACCELEROMETERTYPE._serialized_end=731
  _PROTOBUFTEXTLOGMSG._serialized_start=14
  _PROTOBUFTEXTLOGMSG._serialized_end=48
  _PROTOBUFACCELEROMETERDATAMSG._serialized_start=50
  _PROTOBUFACCELEROMETERDATAMSG._serialized_end=147
  _PROTOBUFMAGNETOMETERDATAMSG._serialized_start=149
  _PROTOBUFMAGNETOMETERDATAMSG._serialized_end=211
  _PROTOBUFBAROMETERDATAMSG._serialized_start=213
  _PROTOBUFBAROMETERDATAMSG._serialized_end=278
  _PROTOBUFGNSSDATAMSG._serialized_start=280
  _PROTOBUFGNSSDATAMSG._serialized_end=386
  _MRASPROTOBUFMSG._serialized_start=389
  _MRASPROTOBUFMSG._serialized_end=674
# @@protoc_insertion_point(module_scope)
