//
// Created by robos on 23/12/2022.
//

#ifndef MRAS_GNSSDATAMSG_H
#define MRAS_GNSSDATAMSG_H

#include "SystemMessage.h"

struct GNSSDataMsg : public SystemMessage {
    explicit GNSSDataMsg(SystemMessageType gnss_msg_type) : SystemMessage(gnss_msg_type) {}


    // Should these be doubles????
    float latitude = 0; /// degrees
    float longitude = 0; /// degrees
    float altitude = 0; /// meters
//    float speed = 0;
//    float heading = 0;
    uint8_t fix_type = 0;
    uint8_t SIV = 0;


//    float hAcc = 0; // Auto generated by copilot - may implement later
//    float vAcc = 0;
//    float sAcc = 0;
//    float cAcc = 0;
//    float gAcc = 0;
//    float pAcc = 0;
//    float tAcc = 0;
//    float headAcc = 0;
//    float headVeh = 0;
//    float magDec = 0; Magnetic declination at that point according to world magnetic model - A great idea by copilot
//    float magAcc = 0;    - Magnetic declination not supported by ublox 8 series /:(


};


#endif //MRAS_GNSSDATAMSG_H
