name: PlatformIO CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull & update submodules recursively
        run: git submodule update --init --recursive
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Build project with `pio run`
        run: pio run
      - name: Run PlatformIO native unit tests
        run: pio test -e native

      - name: Upload artifact of finished build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: .pio/libdeps # or path/to/artifact